from main_content_frames.test_section_frames.testImageDisplaySectionFrame import TestImageDisplaySectionFrame
from main_content_frames.test_section_frames.predictionDisplayFrame import PredictionDisplayFrame
